import {readFile,mkdir,writeFile,copyFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const data=JSON.parse(await readFile(resolve(root,'content/site.json'),'utf8'));
const services=JSON.parse(await readFile(resolve(root,'content/services.json'),'utf8'));
const {business,projects,articles}=data;
const production=process.env.SITE_ENV==='production';
const domain=(process.env.SITE_URL||business.domain).replace(/\/$/,'');
if(production&&!/^https:\/\/[\w.-]+$/.test(domain))throw new Error('SITE_URL must be an HTTPS origin');
const out=resolve(root,'dist');await mkdir(out,{recursive:true});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=s=>JSON.stringify(s).replace(/</g,'\\u003c');
const getProject=slug=>projects.find(p=>p.slug===slug);
const pathOf=p=>'/work/'+p.slug;
const link=(href,text,cls='text-link')=>`<a class="${cls}" href="${esc(href)}">${esc(text)} <span aria-hidden="true">↗</span></a>`;
const mark=`<svg viewBox="0 0 40 40" aria-hidden="true"><path d="M0 0H18V18ZM22 0H40L22 18ZM40 22V40L22 22ZM18 22V40H0Z" fill="currentColor"/></svg>`;
const logo=`<a class="logo" href="/" aria-label="Kyte home">${mark}<span>kyte<small>Design & creative agency</small></span></a>`;
const nav=[['/work','Work'],['/services','Services'],['/about-us','About'],['/design-news','Design News'],['/careers','Careers'],['/contact','Contact']];
function media(im,alt,eager=false,cls=''){
 if(!im?.src)return '';
 return `<img class="${cls}" src="${esc(im.src)}" ${im.srcset?`srcset="${esc(im.srcset)}" sizes="(max-width: 700px) 100vw, (max-width: 1100px) 80vw, 1200px"`:''} alt="${esc(alt)}" width="${esc(im.width||1600)}" height="${esc(im.height||900)}" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''} decoding="async">`;
}
function card(p){return `<article class="work-card" data-category="${esc(p.group)}"><a href="${pathOf(p)}" class="image-link" aria-label="View ${esc(p.name)} project">${media(p.cover,`${p.name}: ${p.role}`)}</a><div class="card-caption"><div><p class="eyebrow">${esc(p.role)}</p><h3><a href="${pathOf(p)}">${esc(p.name)}</a></h3></div><a class="round-link" href="${pathOf(p)}" aria-label="View ${esc(p.name)} project">↗</a></div></article>`}
function workGrid(slugs){return `<div class="work-grid">${slugs.map(getProject).filter(Boolean).map(card).join('')}</div>`}
const header=path=>`<a class="skip" href="#main">Skip to content</a><header class="site-header">${logo}<nav class="desktop-nav" aria-label="Primary">${nav.slice(0,3).map(([href,label])=>`<a href="${href}" ${path===href?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="header-actions"><a class="button compact" href="/contact">Start a project <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-haspopup="dialog" aria-controls="site-menu"><span></span><span></span></button></div></header><dialog id="site-menu" aria-labelledby="menu-title"><div class="menu-top">${logo}<button class="close" data-close aria-label="Close navigation">×</button></div><h2 id="menu-title" class="sr-only">Navigation</h2><nav aria-label="All pages">${[['/','Home'],...nav].map(([href,label],i)=>`<a href="${href}"><span class="eyebrow">0${i+1}</span>${label}<span aria-hidden="true">↗</span></a>`).join('')}</nav><a class="menu-email" href="mailto:${esc(business.email)}">${esc(business.email)}</a></dialog>`;
const cta=()=>`<section class="cta section"><p class="eyebrow">YOUR NEXT CHAPTER</p><h2>What are you<br>working on?</h2><div><p>Tell us where you are, what needs to change<br class="desktop-only"> and what you want to build.</p>${link('/contact','Start a project','button')}</div></section>`;
const footer=()=>`<footer class="site-footer"><div class="footer-top">${logo}<nav aria-label="Footer">${nav.map(([h,t])=>`<a href="${h}">${t}</a>`).join('')}</nav><div><p class="eyebrow">REACH OUT</p><a href="mailto:${esc(business.email)}">${esc(business.email)}</a><p>${esc(business.city)}</p>${business.phone?`<a href="tel:${esc(business.phone.replace(/[^+\d]/g,''))}">${esc(business.phone)}</a>`:''}</div></div><div class="footer-word" aria-hidden="true">kyte®</div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Kyte</span><a href="/privacy">Privacy</a><span>Made to mean something.</span></div></footer>`;
function faq(items){return `<div class="faqs">${items.map(([q,a])=>`<details><summary>${esc(q)}<span aria-hidden="true">+</span></summary><p>${esc(a)}</p></details>`).join('')}</div>`}
function sectionTitle(kicker,title,extra=''){return `<div class="section-heading"><div><p class="eyebrow">${esc(kicker)}</p><h2>${esc(title)}</h2></div>${extra}</div>`}
function serviceRows(){return services.map((s,i)=>`<article class="service-row ${i===0?'service-lead':''}"><div class="service-info"><p class="eyebrow">0${i+1} / ${i===0?'OUR LEAD OFFERING':'SERVICES'}</p><h2><a href="/services/${s.slug}">${esc(s.name)}</a></h2><p class="service-line">${esc(s.line)}</p><p>${esc(s.summary)}</p><ul class="tags">${s.scope.map(([t])=>`<li>${esc(t)}</li>`).join('')}</ul>${link('/services/'+s.slug,'Explore '+s.name)}</div><figure><a href="${pathOf(getProject(s.proof[0]))}" aria-label="View ${esc(getProject(s.proof[0]).name)} project">${media(getProject(s.proof[0]).cover,getProject(s.proof[0]).name+' project')}</a><figcaption>${esc(getProject(s.proof[0]).name)} <span>${esc(getProject(s.proof[0]).role)}</span></figcaption></figure></article>`).join('')}
const hubFAQ=[['Can we start with one service?','Yes. You can work with us on one part of the project or connect several services around a shared brief.'],['Can you work with what we already have?','Yes. Bring your existing product, identity or content. We can agree what should stay, what needs attention and where to start.'],['What should we bring to the first conversation?','A little context about your business, the problem you want to solve, any useful examples and your timing. A finished brief is not required.'],['How is scope agreed?','We discuss the objective, deliverables, responsibilities and review process before work starts. Timing and budget follow the scope.']];
function home(){return `<section class="home-hero section grid-texture"><p class="eyebrow">PRODUCT FIRST. BUILT TO GO FURTHER.</p><h1>Good design.<br>Real <span class="outline">possibilities.</span></h1><div class="hero-bottom"><p>We're Kyte, a UI/UX design agency in India.<br>We shape digital products, build clear brands<br>and bring them into the world.</p>${link('/work','Explore our work','button')}</div><a class="hero-project" href="/work/collectbee-website">${media(getProject('collectbee-website').cover,'Collectbee website design by Kyte',true)}<span>Collectbee <small>Product design & website build</small><b aria-hidden="true">↗</b></span></a></section><section class="section">${sectionTitle('SELECTED WORK','Ideas, out in the world.',link('/work','View all work'))}${workGrid(['ogale-machines-design-development','spicy-tango','smash-guys','revenue-grid-explainer-videos'])}</section><section class="section services-preview">${sectionTitle('WHAT WE DO','Design the product.\nBuild what comes next.')}<p class="section-intro">One partner for the experience, the identity and the stories that carry it forward.</p>${services.map((s,i)=>`<a class="service-strip" href="/services/${s.slug}"><span class="eyebrow">0${i+1}</span><h3>${esc(s.name)}</h3><span aria-hidden="true">↗</span></a>`).join('')}</section><section class="section split-statement"><p class="eyebrow">HOW WE WORK</p><div><h2>Clear thinking.<br>Work you can see.</h2><p>We turn the brief into something tangible early, so you can respond to the direction while there's room to make it better. Then we carry the details through.</p>${link('/about-us','Meet Kyte')}</div></section>${cta()}`}
function hub(){return `<section class="section services-hero grid-texture"><p class="eyebrow">OUR SERVICES</p><h1>Design your product.<br><span class="muted">Bring it to market.</span></h1><div class="hub-intro"><p>We help you shape digital products, build a clear brand, and create the content that introduces it to the world. Start with the part your business needs now.</p>${link('#services','Explore our services','button')}</div></section><section id="services" class="section service-list">${serviceRows()}</section><section class="section">${sectionTitle('CONNECTED BY DESIGN','From the first idea\nto the next chapter.')}<div class="three-grid">${[['01','Shape the product.','Understand the user, decide what matters and design the experience.'],['02','Build a recognizable brand.','Give the product a clear identity and consistent visual language.'],['03','Bring it to people.','Use content, social and video to explain the offer and support launch.']].map(([n,t,p])=>`<article><p class="eyebrow">${n}</p><h3>${t}</h3><p>${p}</p></article>`).join('')}</div><p class="note">You can work with us on one part or several.</p></section><section class="section">${sectionTitle('THE WORK BEHIND THE WORDS','Selected projects.')}${workGrid(['ogale-machines-design-development','spicy-tango','revenue-grid-explainer-videos'])}</section><section class="section faq-section">${sectionTitle('BEFORE WE START','A few useful answers.')}${faq(hubFAQ)}</section>${cta()}`}
function detail(s){const p=getProject(s.proof[0]);return `<section class="section detail-hero grid-texture"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/services">Services</a><span aria-hidden="true">/</span><span>${esc(s.name)}</span></nav><p class="eyebrow">${esc(s.name)}</p><h1>${esc(s.headline)}</h1><div class="hero-bottom"><p>${esc(s.summary)}</p><div class="actions">${link('/contact?service='+s.id,'Discuss your project','button')}${link('#case-work','See relevant work')}</div></div><figure class="wide-media">${media(p.cover,p.name+': '+p.role,true)}<figcaption>${esc(p.name)} <span>${esc(p.role)}</span></figcaption></figure></section><section class="section">${sectionTitle('WHAT WE DO','A clear scope.\nA considered result.')}<div class="scope-grid">${s.scope.map(([t,p],i)=>`<article><p class="eyebrow">0${i+1}</p><h3>${esc(t)}</h3><p>${esc(p)}</p></article>`).join('')}</div></section><section class="section">${sectionTitle('OUR APPROACH','Make the next decision clearer.')}<ol class="process">${s.steps.map(([t,p])=>`<li><h3>${esc(t)}</h3><p>${esc(p)}</p></li>`).join('')}</ol>${s.id==='product'?'<p class="note">Working prototypes help us bring design and build conversations closer together. We use AI-assisted tools where they help explore and iterate, with human review and testing throughout.</p>':''}</section><section class="section">${sectionTitle('WHY KYTE','Thought through.\nCarried through.')}<div class="three-grid">${s.reasons.map(([t,p])=>`<article><h3>${esc(t)}</h3><p>${esc(p)}</p></article>`).join('')}</div></section><section class="section fit-section">${sectionTitle('IS THIS FOR YOU?','You might be here because…')}<ul>${s.fit.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section><section id="case-work" class="section">${sectionTitle('CASE WORK','See it in practice.')}${workGrid(s.proof)}</section><section class="section faq-section">${sectionTitle('QUESTIONS, ANSWERED','Before we begin.')}${faq(s.faqs)}</section>${cta()}`}
function work(){return `<section class="section page-hero"><p class="eyebrow">SELECTED WORK</p><h1>Made with purpose.<br><span class="muted">Made to be seen.</span></h1><p>Digital products, identities and communication.<br>A selection of the work we've put into the world.</p></section><section class="section work-list"><div class="filters" role="group" aria-label="Filter projects"><button aria-pressed="true" data-filter="all">All work <span>${projects.length}</span></button>${services.map(s=>`<button aria-pressed="false" data-filter="${s.id}">${esc(s.name)}</button>`).join('')}</div><p class="sr-only" aria-live="polite" id="filter-status"></p><div class="work-grid">${projects.map(card).join('')}</div></section>${cta()}`}
function project(p){const s=services.find(s=>s.id===p.group);const related=projects.filter(q=>q.slug!==p.slug&&q.group===p.group).slice(0,2);const body=p.body.map(b=>`<${b.type==='h2'?'h2':'p'}>${esc(b.text)}</${b.type==='h2'?'h2':'p'}>`).join('');return `<section class="section project-hero"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/work">Work</a><span aria-hidden="true">/</span><span>${esc(p.name)}</span></nav><p class="eyebrow">${esc(p.role)}</p><h1>${esc(p.name)}</h1><p class="project-summary">${esc(p.summary)}</p><div class="project-meta"><div><span class="eyebrow">CLIENT</span>${esc(p.name)}</div><div><span class="eyebrow">OUR ROLE</span>${esc(p.role)}</div><div><span class="eyebrow">SERVICE</span><a href="/services/${s.slug}">${esc(s.name)}</a></div></div></section><figure class="project-cover">${media(p.cover,p.name+': '+p.role,true)}</figure><section class="section case-body"><aside><p class="eyebrow">THE PROJECT</p><p>${esc(p.name)}</p></aside><div class="prose">${body}</div></section>${p.gallery.filter(im=>im.src?.split('--')[0]!==p.cover.src?.split('--')[0]).map(im=>`<figure class="section project-gallery">${media(im,p.name+' project detail')}</figure>`).join('')}<section class="section">${sectionTitle('KEEP EXPLORING','More work.')}${workGrid(related.map(x=>x.slug))}</section>${cta()}`}
function articleCard(a){return `<article class="article-card"><a class="image-link" href="/design-news/${a.slug}">${media(a.cover,a.title)}</a><p class="eyebrow">${esc(a.category||'DESIGN NEWS')}</p><h3><a href="/design-news/${a.slug}">${esc(a.title)}</a></h3></article>`}
function news(){return `<section class="section page-hero"><p class="eyebrow">DESIGN NEWS</p><h1>A point of view.<br><span class="muted">A reason to look closer.</span></h1><p>Notes on design, culture and the things<br>that make people pay attention.</p></section><section class="section"><div class="article-grid">${articles.map(articleCard).join('')}</div></section>${cta()}`}
function article(a){return `<section class="section article-hero"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/design-news">Design News</a><span aria-hidden="true">/</span><span>Article</span></nav><p class="eyebrow">${esc(a.category)}</p><h1>${esc(a.title)}</h1><p>${esc(a.description)}</p><p class="byline">By ${esc(a.author||'Kyte')}</p></section><figure class="project-cover article-cover">${media(a.cover,a.title,true)}</figure><article class="section article-body prose">${a.paragraphs.map(p=>{const h=/^(?:[IVX]+\.|\d+\.)/.test(p)&&p.length<110;return `<${h?'h2':'p'}>${esc(p)}</${h?'h2':'p'}>`}).join('')}<aside class="article-next"><h2>Bring the idea into your brand.</h2><p>Explore how our branding and content work connects design with the way people see a business.</p>${link('/services/branding-graphic-design','Branding & Graphic Design')}${link('/services/social-media-content','Social Media & Content')}</aside></article><section class="section">${sectionTitle('CONTINUE READING','More perspectives.')}<div class="article-grid">${articles.filter(b=>b.slug!==a.slug).slice(0,3).map(articleCard).join('')}</div></section>${cta()}`}
function about(){return `<section class="section page-hero grid-texture"><p class="eyebrow">ABOUT KYTE</p><h1>Curious people.<br><span class="muted">Considered work.</span></h1><p>We're a design and creative agency based in India.<br>We help you shape the product, build the brand<br>and carry the story into the world.</p></section><section class="section split-statement"><p class="eyebrow">OUR APPROACH</p><div><h2>We like making<br>things make sense.</h2><p>Clear thinking sits behind the work. We ask questions, make ideas tangible and pay attention to how the details fit together.</p><p>Our practice spans product and UI/UX design, branding, content and video. That gives us room to consider the experience as a whole, from what people use to what they see and hear about it.</p></div></section><section class="section">${sectionTitle('HOW WE SHOW UP','A few things we work by.')}<div class="scope-grid">${[['Think clearly','Understand the problem before rushing to an answer.'],['Stay curious','Ask questions and leave room for a better direction.'],['Make better','Use feedback to refine the work, not just add another version.'],['Ship well','Carry the detail through to the final experience.']].map(([t,p])=>`<article><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section><section class="section">${sectionTitle('THE PEOPLE','Small conversations.\nShared ambition.')}<p class="section-intro">Kyte is led by Vedant Malkarnekar and Varun Padmanabhan, working with a team across design, content and production.</p>${link('/contact','Get to know us')}</section>${cta()}`}
const field=(name,label,type='text',required=false)=>`<label>${label}${required?' <span aria-hidden="true">*</span>':''}<input name="${name}" type="${type}" ${required?'required':''} ${name==='name'?'autocomplete="name"':name==='email'?'autocomplete="email"':name==='company'?'autocomplete="organization"':''} maxlength="${name==='email'?254:160}"></label>`;
function contact(){return `<section class="section page-hero"><p class="eyebrow">LET'S TALK</p><h1>What are you<br><span class="muted">working on?</span></h1></section><section class="section contact-grid"><div><h2>A little context.<br>A good place to start.</h2><p>Tell us about your business, what you want to change and any timing you have in mind.</p><p>Prefer email?</p><a class="contact-email" href="mailto:${esc(business.email)}">${esc(business.email)}</a><p>${esc(business.city)}</p>${business.address?`<p>${esc(business.address)}</p>`:''}${business.phone?`<a href="tel:${esc(business.phone.replace(/[^+\d]/g,''))}">${esc(business.phone)}</a>`:''}</div><form id="inquiry" action="/api/inquiry" method="post"><p class="form-note">Fields marked * are required.</p><div class="form-row">${field('name','Name','text',true)}${field('email','Email','email',true)}</div>${field('company','Company')}<label>I'm interested in<select name="service"><option value="">Let's figure it out</option>${services.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label>Tell us about your project <span aria-hidden="true">*</span><textarea name="message" required minlength="10" maxlength="5000" rows="5"></textarea></label><div class="honeypot" aria-hidden="true"><label>Leave this empty<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="form-note">We'll use these details to respond to your inquiry. <a href="/privacy">Privacy information</a>.</p><button class="button" type="submit">Send inquiry <span aria-hidden="true">↗</span></button><p id="form-status" role="status" aria-live="polite"></p><a id="email-fallback" href="mailto:${esc(business.email)}" hidden>Send your brief by email instead ↗</a><noscript><p>This preview form needs JavaScript for inline status. You can always email ${esc(business.email)}.</p></noscript></form></section>`}
function careers(){return `<section class="section page-hero grid-texture"><p class="eyebrow">CAREERS AT KYTE</p><h1>Bring your curiosity.<br><span class="muted">Make good work.</span></h1><p>We like people who ask thoughtful questions,<br>care about the details and enjoy making things together.</p></section><section class="section split-statement"><p class="eyebrow">INTRODUCE YOURSELF</p><div><h2>Let your work<br>start the conversation.</h2><p>Share your portfolio, the kind of work you enjoy and a little about yourself. We'll use your introduction to understand where your skills might fit.</p><p>Specific openings will appear here when they are confirmed.</p>${link('mailto:'+business.email+'?subject=Portfolio%20introduction','Email your portfolio','button')}</div></section>`}
function privacy(){return `<section class="section page-hero"><p class="eyebrow">YOUR INFORMATION</p><h1>Privacy</h1></section><section class="section prose"><h2>Project inquiries</h2><p>When you contact Kyte, the details you provide are used to understand and respond to your inquiry. Please avoid including sensitive personal information in your message.</p><h2>Your choices</h2><p>You can ask about your inquiry information or request its deletion by emailing <a href="mailto:${esc(business.email)}">${esc(business.email)}</a>.</p><h2>This website</h2><p>This build does not load advertising trackers or set analytics cookies. External links and your email provider are subject to their own privacy practices.</p><h2>Contact</h2><p>${esc(business.email)}</p></section>`}
const pages=[];
async function page(path,title,description,body,{image,articleData,noindex=false}={}){
 const canonical=domain+path;const breadcrumbs=path==='/'?null:{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:domain+'/'},...(path.split('/').filter(Boolean).length>1?[{'@type':'ListItem',position:2,name:path.startsWith('/work')?'Work':path.startsWith('/services')?'Services':'Design News',item:domain+'/'+path.split('/')[1]}]:[]),{'@type':'ListItem',position:path.split('/').filter(Boolean).length>1?3:2,name:title.split(' · ')[0],item:canonical}]};
 const schema={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':domain+'/#organization',name:'Kyte',url:domain,email:business.email},...(breadcrumbs?[breadcrumbs]:[]),...(articleData?[{'@type':'Article',headline:articleData.title,description,author:{'@type':'Person',name:articleData.author||'Kyte'},publisher:{'@id':domain+'/#organization'},mainEntityOfPage:canonical,...(image?{image:domain+image}:{})}]:[])]};
 const share=image||getProject('collectbee-website').cover.src;
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${!production||noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="${articleData?'article':'website'}"><meta property="og:site_name" content="Kyte"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="${esc(domain+share)}"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#101010"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/site.css"><script src="/site.js" defer></script><script type="application/ld+json">${json(schema)}</script></head><body>${header(path)}<main id="main">${body}</main>${footer()}</body></html>`;
 const dest=resolve(out,'.'+(path==='/'?'':path),'index.html');await mkdir(dirname(dest),{recursive:true});await writeFile(dest,html);if(!noindex)pages.push({path,title,description});
}
await page('/','UI/UX Design Agency in India · Kyte','Kyte designs digital products, builds clear brands and creates content that brings them into the world. Explore our work and services.',home());
await page('/services','Design, Branding & Content Services · Kyte','Explore Product & UI/UX Design, Branding & Graphic Design, Social Media & Content, and Video & Animation with Kyte.',hub());
for(const s of services)await page('/services/'+s.slug,({'product':'Website & UI/UX Design Agency in India','branding':'Branding & Graphic Design Agency in India','social':'Social Media & Content Agency in India','video':'Video Production & Animation in India'}[s.id])+' · Kyte',s.description,detail(s),{image:getProject(s.proof[0]).cover.src});
await page('/work','Selected Design & Branding Work · Kyte','Explore selected Kyte projects across website and product design, brand identity, social content and video.',work());
for(const p of projects)await page(pathOf(p),p.name+' · '+p.role+' · Kyte',p.summary,project(p),{image:p.cover.src});
await page('/design-news','Design News & Perspectives · Kyte','Read perspectives from Kyte on design, branding, culture and the things that make people pay attention.',news());
for(const a of articles)await page('/design-news/'+a.slug,a.title+' · Kyte',a.description||a.paragraphs[0],article(a),{image:a.cover.src,articleData:a});
await page('/about-us','About Kyte · Our Team and Approach','Meet Kyte, a design and creative agency working across digital products, branding, content and video.',about());
await page('/contact','Contact Kyte · Tell Us About Your Project','Tell Kyte about your next website, digital product, branding or content project. Start a conversation with our team.',contact());
await page('/careers','Careers at Kyte · Introduce Yourself','Introduce yourself to Kyte. Share your portfolio and the design, content or production work you care about.',careers());
await page('/privacy','Privacy · Kyte','How Kyte uses project inquiry details and how to contact us about your information.',privacy());
await page('/404','Page Not Found · Kyte','This page could not be found. Explore Kyte’s work and services.',`<section class="section page-hero"><p class="eyebrow">404</p><h1>A different direction?</h1><p>We couldn't find that page.</p>${link('/','Back to Kyte','button')}</section>`,{noindex:true});
await writeFile(resolve(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${esc(domain+p.path)}</loc></url>`).join('')}</urlset>`);
await writeFile(resolve(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${domain}/sitemap.xml\n`);
await writeFile(resolve(out,'favicon.svg'),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" fill="#101010"/><path d="M3 3H18V18ZM22 3H37L22 18ZM37 22V37L22 22ZM18 22V37H3Z" fill="white"/></svg>`);
for(const f of ['site.css','site.js'])await copyFile(resolve(root,'src',f),resolve(out,f));
await writeFile(resolve(out,'pages.json'),JSON.stringify({production,domain,pages},null,2));
console.log(`Built ${pages.length} pages and 404. Mode: ${production?'production':'preview (noindex)'}`);
